language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - HYDRA_LAUNCHER=fork
    - OMPI_MCA_rmaps_base_oversubscribe=yes
    - MPI=mpich
    - CCTOOLS_VERSION=7.0.11

before_install:
    - sudo apt-get update -q
    - python$PY -m pip install Cython
    - python$PY -m pip install numpy
    - python$PY --version
    - python$PY -m cython --version
    - python$PY -c "import numpy;print(numpy.__version__)"


# install parsl with no optional extras
install:
    - pip install .

# Os tests
os:
    - linux

# command to run tests
script:
    - pip install -r test-requirements.txt
    - bash parsl/tests/run.sh
