from paramiko.util import ClosingContextManager
from typing import Any, Optional
from paramiko.transport import Transport

class SSHClient(ClosingContextManager):
    _transport: Transport
    def __init__(self) -> None: ...
    def load_system_host_keys(self, filename: Optional[Any] = ...) -> None: ...
    def load_host_keys(self, filename: Any) -> None: ...
    def save_host_keys(self, filename: Any) -> None: ...
    def get_host_keys(self) -> Any: ...
    def set_log_channel(self, name: Any) -> None: ...
    def set_missing_host_key_policy(self, policy: Any) -> None: ...
    def connect(self, hostname: Any, port: Any = ..., username: Optional[Any] = ..., password: Optional[Any] = ..., pkey: Optional[Any] = ..., key_filename: Optional[Any] = ..., timeout: Optional[Any] = ..., allow_agent: bool = ..., look_for_keys: bool = ..., compress: bool = ..., sock: Optional[Any] = ..., gss_auth: bool = ..., gss_kex: bool = ..., gss_deleg_creds: bool = ..., gss_host: Optional[Any] = ..., banner_timeout: Optional[Any] = ..., auth_timeout: Optional[Any] = ..., gss_trust_dns: bool = ..., passphrase: Optional[Any] = ..., disabled_algorithms: Optional[Any] = ...) -> Any: ...
    def close(self) -> None: ...
    def exec_command(self, command: Any, bufsize: int = ..., timeout: Optional[Any] = ..., get_pty: bool = ..., environment: Optional[Any] = ...) -> Any: ...
    def invoke_shell(self, term: str = ..., width: int = ..., height: int = ..., width_pixels: int = ..., height_pixels: int = ..., environment: Optional[Any] = ...) -> Any: ...
    def open_sftp(self) -> Any: ...
    def get_transport(self) -> Any: ...

class MissingHostKeyPolicy:
    def missing_host_key(self, client: Any, hostname: Any, key: Any) -> None: ...

class AutoAddPolicy(MissingHostKeyPolicy):
    def missing_host_key(self, client: Any, hostname: Any, key: Any) -> None: ...

class RejectPolicy(MissingHostKeyPolicy):
    def missing_host_key(self, client: Any, hostname: Any, key: Any) -> None: ...

class WarningPolicy(MissingHostKeyPolicy):
    def missing_host_key(self, client: Any, hostname: Any, key: Any) -> None: ...
