from paramiko.common import DEBUG as DEBUG, max_byte as max_byte, xffffffff as xffffffff, zero_byte as zero_byte
from paramiko.config import SSHConfig as SSHConfig
from paramiko.py3compat import PY2 as PY2, b as b, byte_chr as byte_chr, byte_ord as byte_ord, long as long
from typing import Any

def inflate_long(s: Any, always_positive: bool = ...) -> Any: ...

deflate_zero: Any
deflate_ff: Any

def deflate_long(n: Any, add_sign_padding: bool = ...) -> Any: ...
def format_binary(data: Any, prefix: str = ...) -> Any: ...
def format_binary_line(data: Any) -> Any: ...
def safe_string(s: Any) -> Any: ...
def bit_length(n: Any) -> Any: ...
def tb_strings() -> Any: ...
def generate_key_bytes(hash_alg: Any, salt: Any, key: Any, nbytes: Any) -> Any: ...
def load_host_keys(filename: Any) -> Any: ...
def parse_ssh_config(file_obj: Any) -> Any: ...
def lookup_ssh_host_config(hostname: Any, config: Any) -> Any: ...
def mod_inverse(x: Any, m: Any) -> Any: ...
def get_thread_id() -> Any: ...
def log_to_file(filename: Any, level: Any = ...) -> None: ...

class PFilter:
    def filter(self, record: Any) -> Any: ...

def get_logger(name: Any) -> Any: ...
def retry_on_signal(function: Any) -> Any: ...
def constant_time_bytes_eq(a: Any, b: Any) -> Any: ...

class ClosingContextManager:
    def __enter__(self) -> None: ...
    def __exit__(self, type: Any, value: Any, traceback: Any) -> None: ...

def clamp_value(minimum: Any, val: Any, maximum: Any) -> Any: ...
