[package]
name = "rusterchange"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.10.0"
serde-pickle = "1.1.1"
serde_json = "1.0.115"
queues = "1.1.0"
