from __future__ import annotations

import logging
import warnings
from typing import Dict, Optional, Sequence

from parsl.executors import HighThroughputExecutor
from parsl.executors.base import ParslExecutor
from parsl.executors.status_handling import BlockProviderExecutor
from parsl.jobs.strategies.base import ScalingStrategy
from parsl.jobs.strategies.htex_auto_scale import HtexAutoScaleStrategy
from parsl.jobs.strategies.none import InitOnlyStrategy
from parsl.jobs.strategies.simple import SimpleStrategy

logger = logging.getLogger(__name__)


class Strategy:
    """Scaling strategy.

    As a workflow dag is processed by Parsl, new tasks are added and completed
    asynchronously. Parsl interfaces executors with execution providers to construct
    scalable executors to handle the variable work-load generated by the
    workflow. This component is responsible for periodically checking outstanding
    tasks and available compute capacity and trigger scaling events to match
    workflow needs.

    Here's a diagram of an executor. An executor consists of blocks, which are usually
    created by single requests to a Local Resource Manager (LRM) such as slurm,
    condor, torque, or even AWS API. The blocks could contain several task blocks
    which are separate instances on workers.


    .. code:: python

                |<--min_blocks     |<-init_blocks              max_blocks-->|
                +----------------------------------------------------------+
                |  +--------block----------+       +--------block--------+ |
     executor = |  | task          task    | ...   |    task      task   | |
                |  +-----------------------+       +---------------------+ |
                +----------------------------------------------------------+

    The relevant specification options are:
       1. min_blocks: Minimum number of blocks to maintain
       2. init_blocks: number of blocks to provision at initialization of workflow
       3. max_blocks: Maximum number of blocks that can be active due to one workflow


    .. code:: python

          active_tasks = pending_tasks + running_tasks

          Parallelism = slots / tasks
                      = [0, 1] (i.e,  0 <= p <= 1)

    For example:

    When p = 0,
         => compute with the least resources possible.
         infinite tasks are stacked per slot.

         .. code:: python

               blocks =  min_blocks           { if active_tasks = 0
                         max(min_blocks, 1)   {  else

    When p = 1,
         => compute with the most resources.
         one task is stacked per slot.

         .. code:: python

               blocks = min ( max_blocks,
                        ceil( active_tasks / slots ) )


    When p = 1/2,
         => We stack upto 2 tasks per slot before we overflow
         and request a new block


    let's say min:init:max = 0:0:4 and task_blocks=2
    Consider the following example:
    min_blocks = 0
    init_blocks = 0
    max_blocks = 4
    tasks_per_node = 2
    nodes_per_block = 1

    In the diagram, X <- task

    at 2 tasks:

    .. code:: python

        +---Block---|
        |           |
        | X      X  |
        |slot   slot|
        +-----------+

    at 5 tasks, we overflow as the capacity of a single block is fully used.

    .. code:: python

        +---Block---|       +---Block---|
        | X      X  | ----> |           |
        | X      X  |       | X         |
        |slot   slot|       |slot   slot|
        +-----------+       +-----------+

    """

    def __init__(self, *, strategy: Optional[str], max_idletime: float) -> None:
        self.max_idletime = max_idletime
        self._strategies_by_executor: Dict[str, ScalingStrategy] = {}

        self._strategy_name = strategy
        if strategy is None:
            warnings.warn(
                "literal None for strategy choice is deprecated. Use string 'none' instead.",
                DeprecationWarning,
            )

        logger.debug("Scaling strategy: {0}".format(strategy))

    def add_executors(self, executors: Sequence[ParslExecutor]) -> None:
        for executor in executors:
            if not isinstance(executor, BlockProviderExecutor):
                continue

            self._configure_executor(executor)

    def strategize(self, executors: Sequence[BlockProviderExecutor]) -> None:
        for executor in executors:
            strategy = self._strategies_by_executor.get(executor.label)

            if strategy is None:
                strategy = self._configure_executor(executor)

            strategy.strategize()

    def _configure_executor(self, executor: BlockProviderExecutor) -> ScalingStrategy:
        strategy = self._make_strategy(executor)
        self._strategies_by_executor[executor.label] = strategy
        return strategy

    def _make_strategy(self, executor: BlockProviderExecutor) -> ScalingStrategy:
        strategy_name = self._strategy_name

        if strategy_name in (None, "none"):
            return InitOnlyStrategy(executor)

        if strategy_name == "simple":
            return SimpleStrategy(executor, self.max_idletime)

        if strategy_name == "htex_auto_scale":
            if isinstance(executor, HighThroughputExecutor):
                return HtexAutoScaleStrategy(executor, self.max_idletime)

            raise TypeError(
                f"[Scaling executor {executor.label}] This strategy only supports scaling in for HighThroughputExecutor "
                  "- taking no action", executor.label)

        raise ValueError(f"Unknown strategy: {strategy_name!r}")
