#!/bin/bash

set -e

usage() {
    echo "Usage: python_package_analyze [options] <environment-name> <python-command-string>"
    echo "where options are:"
    echo -e " -h, --help\tShow this help screen"
    exit "$1"
}

# Parse command line arguments
if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage 0
fi
if [ $# -lt 2 ]; then
    usage 1
fi

unset ENVDIR
function cleanup {
    rm -rf "$ENVDIR"
}
trap cleanup EXIT
ENVDIR="$(mktemp -d)"

tar -xaf "$1" -C "$ENVDIR"

set +e
source "$ENVDIR/bin/activate" || exit 1
conda-unpack || exit 1

"${@:2}"
