name: Test Parsl with Flux Scheduler
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  main-test-suite:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    strategy:
      fail-fast: false
      matrix:
        container: ['fluxrm/flux-sched:focal']

    container:
      image: ${{ matrix.container }}
      options: "--platform=linux/amd64 --user root -it --init"

    name: ${{ matrix.container }}
    steps:
      - name: Make Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc

      - name: Checkout Parsl
        uses: actions/checkout@v3
        with:
          repository: 'parsl/parsl'
          ref: 'main' # or any specific branch

      - name: Install Parsl and Dependencies
        run: |
          apt-get update && apt-get install -y python3-pip curl
          pip3 install -r requirements.txt
          python3 setup.py install

      - name: Start Flux and Run Test
        run: |
          # Start Flux and run tests with Parsl
          # Replace this section with actual commands to start Flux and test Parsl with it
          echo "Starting Flux and running tests with Parsl..."