name: Test HTCondor Scheduler
on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: read
    strategy:
      fail-fast: true
      matrix:
        container: ["htcondor/mini:latest"]
    timeout-minutes: 30

    container:
      image: ${{ matrix.container }}
      options: "--platform=linux/amd64 --rm -h node01"

    name: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies and Parsl
        run: |
          dnf install -y python3.12 python3-virtualenv
          su - submituser -c bash -c "echo cp -av ${GITHUB_WORKSPACE}/ ./"
          su - submituser -c bash -c "cp -av ${GITHUB_WORKSPACE}/* ./"
          su - submituser -c bash -c "virtualenv ./venv --python=3.12"
          su - submituser -c bash -c ". ./venv/bin/activate ; pip install . -r test-requirements.txt"

      - name: Verify Parsl Installation
        run: |
          su - submituser -c bash -c '. venv/bin/activate ; pytest parsl/tests/ -k "not cleannet and not unix_filesystem_permissions_required" --config parsl/tests/configs/local_threads.py --random-order --durations 10'

      - name: Test Parsl with HTCondor Config
        run: |
          (/start.sh &) && su - submituser -c bash -c '. venv/bin/activate ; sleep 20s && pytest parsl/tests/ -k "not cleannet and not unix_filesystem_permissions_required" --config parsl/tests/configs/htcondor_local.py --random-order --durations 10'
